Member_03_DistilBERT_Progress.ipynb

In [27]:
!pip install transformers datasets torch scikit-learn streamlit -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 65.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 54.4 MB/s eta 0:00:00

In [2]:
import pandas as pd
import numpy as np
import torch

from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification

In [25]:
import zipfile

with zipfile.ZipFile('/content/train.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')
print('train.csv extracted successfully.')

train.csv extracted successfully.

In [26]:
df = pd.read_csv("/content/train.csv")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (159571, 8)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [7]:
df = pd.read_csv("/content/train.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (159571, 8)

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [8]:
labels = [
    "toxic",
    "severe_toxic",
    "obscene",
    "threat",
    "insult",
    "identity_hate"
]

print("Target labels:")
print(labels)

print("\nLabel counts:")
print(df[labels].sum())

Target labels:
['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

Label counts:
toxic            15294
severe_toxic      1595
obscene           8449
threat             478
insult            7877
identity_hate     1405
dtype: int64

In [9]:
sample_text = "You are stupid and I hate you."

print("Sample comment:")
print(sample_text)

Sample comment:
You are stupid and I hate you.

In [10]:
tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)

print("Tokenizer loaded successfully.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenizer loaded successfully.

In [11]:
tokens = tokenizer.tokenize(sample_text)

print("Original text:")
print(sample_text)

print("\nTokens:")
print(tokens)

Original text:
You are stupid and I hate you.

Tokens:
['you', 'are', 'stupid', 'and', 'i', 'hate', 'you', '.']

In [12]:
encoded_input = tokenizer(
    sample_text,
    padding="max_length",
    truncation=True,
    max_length=32,
    return_tensors="pt"
)

print("Encoded input created successfully.")

Encoded input created successfully.

In [13]:
print("Input IDs:")
print(encoded_input["input_ids"])

print("\nInput IDs shape:")
print(encoded_input["input_ids"].shape)

Input IDs:
tensor([[ 101, 2017, 2024, 5236, 1998, 1045, 5223, 2017, 1012,  102,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]])

Input IDs shape:
torch.Size([1, 32])

In [14]:
print("Attention Mask:")
print(encoded_input["attention_mask"])

print("\nAttention Mask shape:")
print(encoded_input["attention_mask"].shape)

Attention Mask:
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])

Attention Mask shape:
torch.Size([1, 32])

In [15]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=6,
    problem_type="multi_label_classification"
)

print("DistilBERT model loaded successfully.")

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

DistilBERT model loaded successfully.

In [16]:
print(model)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=6, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [17]:
model.eval()

with torch.no_grad():
    outputs = model(**encoded_input)

print("Raw logits:")
print(outputs.logits)

Raw logits:
tensor([[ 0.1038,  0.1965,  0.1380, -0.0316, -0.0171, -0.0688]])

In [18]:
probabilities = torch.sigmoid(outputs.logits)

print("Probability scores:")
print(probabilities)

Probability scores:
tensor([[0.5259, 0.5490, 0.5345, 0.4921, 0.4957, 0.4828]])

In [19]:
prediction_results = {
    label: float(score)
    for label, score in zip(labels, probabilities[0])
}

for label, score in prediction_results.items():
    print(f"{label}: {score:.4f}")

toxic: 0.5259
severe_toxic: 0.5490
obscene: 0.5345
threat: 0.4921
insult: 0.4957
identity_hate: 0.4828

In [20]:
def predict_toxicity(text):
    encoded = tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=32,
        return_tensors="pt"
    )

    model.eval()

    with torch.no_grad():
        output = model(**encoded)

    scores = torch.sigmoid(output.logits)[0]

    results = {
        label: round(float(score), 4)
        for label, score in zip(labels, scores)
    }

    return results

In [21]:
test_comment = "You are stupid and I hate you."

results = predict_toxicity(test_comment)

print("Input comment:")
print(test_comment)

print("\nPrediction results:")
for label, score in results.items():
    print(f"{label}: {score}")

Input comment:
You are stupid and I hate you.

Prediction results:
toxic: 0.5259
severe_toxic: 0.549
obscene: 0.5345
threat: 0.4921
insult: 0.4957
identity_hate: 0.4828

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.multiclass import OneVsRestClassifier

rf_model = OneVsRestClassifier(
    RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )
)

print(rf_model)

OneVsRestClassifier(estimator=RandomForestClassifier(n_jobs=-1,
                                                     random_state=42))

In [28]:
import streamlit as st

st.title("Toxic Comment Detection")

comment = st.text_area("Enter a comment")

if st.button("Analyze"):
    if comment.strip():
        st.write("Comment received for toxicity analysis.")
    else:
        st.warning("Please enter a comment.")

2026-07-31 05:01:26.138 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.265
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-07-31 05:01:26.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.270 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.273 Session state does not function when running a script without `streamlit run`
2026-07-31 05:01:26.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-31 05:01:26.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [32]:
!streamlit run app.py

Usage: streamlit run [OPTIONS] [TARGET] [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: app.py